//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLSim.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.0")]
        public string ProSimIP {
            get {
                return ((string)(this["ProSimIP"]));
            }
            set {
                this["ProSimIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoConnect {
            get {
                return ((bool)(this["AutoConnect"]));
            }
            set {
                this["AutoConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int AP_Disconnet_Roll_Threshold {
            get {
                return ((int)(this["AP_Disconnet_Roll_Threshold"]));
            }
            set {
                this["AP_Disconnet_Roll_Threshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int AP_Disconnet_Pitch_Threshold {
            get {
                return ((int)(this["AP_Disconnet_Pitch_Threshold"]));
            }
            set {
                this["AP_Disconnet_Pitch_Threshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Torque_Factor_Air_Speed {
            get {
                return ((int)(this["Torque_Factor_Air_Speed"]));
            }
            set {
                this["Torque_Factor_Air_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Torque_Pitch_Min {
            get {
                return ((int)(this["Torque_Pitch_Min"]));
            }
            set {
                this["Torque_Pitch_Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public int Torque_Pitch_Hyd_Off {
            get {
                return ((int)(this["Torque_Pitch_Hyd_Off"]));
            }
            set {
                this["Torque_Pitch_Hyd_Off"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int Torque_Pitch_Max {
            get {
                return ((int)(this["Torque_Pitch_Max"]));
            }
            set {
                this["Torque_Pitch_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int Torque_Roll_Min {
            get {
                return ((int)(this["Torque_Roll_Min"]));
            }
            set {
                this["Torque_Roll_Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public int Torque_Roll_Hyd_Off {
            get {
                return ((int)(this["Torque_Roll_Hyd_Off"]));
            }
            set {
                this["Torque_Roll_Hyd_Off"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int TrimFactor_Aileron {
            get {
                return ((int)(this["TrimFactor_Aileron"]));
            }
            set {
                this["TrimFactor_Aileron"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2000")]
        public int Position_Pitch_HYD_OFF_Max {
            get {
                return ((int)(this["Position_Pitch_HYD_OFF_Max"]));
            }
            set {
                this["Position_Pitch_HYD_OFF_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public int AP_Position_Roll_Factor {
            get {
                return ((int)(this["AP_Position_Roll_Factor"]));
            }
            set {
                this["AP_Position_Roll_Factor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int RS485COM_Port {
            get {
                return ((int)(this["RS485COM_Port"]));
            }
            set {
                this["RS485COM_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int Torque_Yaw_Hyd_Off {
            get {
                return ((int)(this["Torque_Yaw_Hyd_Off"]));
            }
            set {
                this["Torque_Yaw_Hyd_Off"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Torque_Yaw_Min {
            get {
                return ((int)(this["Torque_Yaw_Min"]));
            }
            set {
                this["Torque_Yaw_Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1000")]
        public int Position_Yaw_HYD_OFF_Max {
            get {
                return ((int)(this["Position_Yaw_HYD_OFF_Max"]));
            }
            set {
                this["Position_Yaw_HYD_OFF_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int TrimFactor_Rudder {
            get {
                return ((int)(this["TrimFactor_Rudder"]));
            }
            set {
                this["TrimFactor_Rudder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Enable_Yaw_ACL {
            get {
                return ((bool)(this["Enable_Yaw_ACL"]));
            }
            set {
                this["Enable_Yaw_ACL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Driver_Yaw_ID {
            get {
                return ((int)(this["Driver_Yaw_ID"]));
            }
            set {
                this["Driver_Yaw_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Driver_Pitch_ID {
            get {
                return ((int)(this["Driver_Pitch_ID"]));
            }
            set {
                this["Driver_Pitch_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Driver_Roll_ID {
            get {
                return ((int)(this["Driver_Roll_ID"]));
            }
            set {
                this["Driver_Roll_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Enable_Pitch_ACL {
            get {
                return ((bool)(this["Enable_Pitch_ACL"]));
            }
            set {
                this["Enable_Pitch_ACL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Enable_Roll_ACL {
            get {
                return ((bool)(this["Enable_Roll_ACL"]));
            }
            set {
                this["Enable_Roll_ACL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int Centering_Speed_Pitch {
            get {
                return ((int)(this["Centering_Speed_Pitch"]));
            }
            set {
                this["Centering_Speed_Pitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int Dampening_Pitch {
            get {
                return ((int)(this["Dampening_Pitch"]));
            }
            set {
                this["Dampening_Pitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Centering_Speed_Roll {
            get {
                return ((int)(this["Centering_Speed_Roll"]));
            }
            set {
                this["Centering_Speed_Roll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Dampening_Roll {
            get {
                return ((int)(this["Dampening_Roll"]));
            }
            set {
                this["Dampening_Roll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Centering_Speed_Yaw {
            get {
                return ((int)(this["Centering_Speed_Yaw"]));
            }
            set {
                this["Centering_Speed_Yaw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Dampening_Yaw {
            get {
                return ((int)(this["Dampening_Yaw"]));
            }
            set {
                this["Dampening_Yaw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Direction_Axis_Pitch {
            get {
                return ((int)(this["Direction_Axis_Pitch"]));
            }
            set {
                this["Direction_Axis_Pitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Direction_Axis_Roll {
            get {
                return ((int)(this["Direction_Axis_Roll"]));
            }
            set {
                this["Direction_Axis_Roll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Direction_Axis_Yaw {
            get {
                return ((int)(this["Direction_Axis_Yaw"]));
            }
            set {
                this["Direction_Axis_Yaw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Auto_Center_On_Start {
            get {
                return ((bool)(this["Auto_Center_On_Start"]));
            }
            set {
                this["Auto_Center_On_Start"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Center_Calibration_Speed_Pitch {
            get {
                return ((int)(this["Center_Calibration_Speed_Pitch"]));
            }
            set {
                this["Center_Calibration_Speed_Pitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int Center_Calibration_Speed_Roll {
            get {
                return ((int)(this["Center_Calibration_Speed_Roll"]));
            }
            set {
                this["Center_Calibration_Speed_Roll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int Center_Calibration_Speed_Yaw {
            get {
                return ((int)(this["Center_Calibration_Speed_Yaw"]));
            }
            set {
                this["Center_Calibration_Speed_Yaw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int AP_Position_Pitch_Factor {
            get {
                return ((int)(this["AP_Position_Pitch_Factor"]));
            }
            set {
                this["AP_Position_Pitch_Factor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Arduino_COM_Port {
            get {
                return ((int)(this["Arduino_COM_Port"]));
            }
            set {
                this["Arduino_COM_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Torque_Tiller_Max {
            get {
                return ((int)(this["Torque_Tiller_Max"]));
            }
            set {
                this["Torque_Tiller_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Torque_Tiller_Hyd_Off {
            get {
                return ((int)(this["Torque_Tiller_Hyd_Off"]));
            }
            set {
                this["Torque_Tiller_Hyd_Off"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Enable_Tiller_ACL {
            get {
                return ((bool)(this["Enable_Tiller_ACL"]));
            }
            set {
                this["Enable_Tiller_ACL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Driver_Tiller_ID {
            get {
                return ((int)(this["Driver_Tiller_ID"]));
            }
            set {
                this["Driver_Tiller_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Dampening_Tiller {
            get {
                return ((int)(this["Dampening_Tiller"]));
            }
            set {
                this["Dampening_Tiller"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int Center_Calibration_Speed_Tiller {
            get {
                return ((int)(this["Center_Calibration_Speed_Tiller"]));
            }
            set {
                this["Center_Calibration_Speed_Tiller"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Direction_Axis_Tiller {
            get {
                return ((int)(this["Direction_Axis_Tiller"]));
            }
            set {
                this["Direction_Axis_Tiller"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Centering_Speed_Tiller {
            get {
                return ((int)(this["Centering_Speed_Tiller"]));
            }
            set {
                this["Centering_Speed_Tiller"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Torque_Tiller_Diff_Offset {
            get {
                return ((int)(this["Torque_Tiller_Diff_Offset"]));
            }
            set {
                this["Torque_Tiller_Diff_Offset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int Torque_Tiller_Min {
            get {
                return ((int)(this["Torque_Tiller_Min"]));
            }
            set {
                this["Torque_Tiller_Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int Torque_Pitch_Axis_Factor {
            get {
                return ((int)(this["Torque_Pitch_Axis_Factor"]));
            }
            set {
                this["Torque_Pitch_Axis_Factor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Torque_Stalling_Additional {
            get {
                return ((int)(this["Torque_Stalling_Additional"]));
            }
            set {
                this["Torque_Stalling_Additional"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int Torque_Roll_Max {
            get {
                return ((int)(this["Torque_Roll_Max"]));
            }
            set {
                this["Torque_Roll_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.254")]
        public string RS485_Pitch {
            get {
                return ((string)(this["RS485_Pitch"]));
            }
            set {
                this["RS485_Pitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int Torque_Yaw_Max {
            get {
                return ((int)(this["Torque_Yaw_Max"]));
            }
            set {
                this["Torque_Yaw_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RS485_Roll {
            get {
                return ((string)(this["RS485_Roll"]));
            }
            set {
                this["RS485_Roll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RS485_Yaw {
            get {
                return ((string)(this["RS485_Yaw"]));
            }
            set {
                this["RS485_Yaw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RS485_Tiller {
            get {
                return ((string)(this["RS485_Tiller"]));
            }
            set {
                this["RS485_Tiller"] = value;
            }
        }
    }
}
