//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLSim.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.0")]
        public string ProSimIP {
            get {
                return ((string)(this["ProSimIP"]));
            }
            set {
                this["ProSimIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int Position_Pitch_Max {
            get {
                return ((int)(this["Position_Pitch_Max"]));
            }
            set {
                this["Position_Pitch_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int Position_Roll_Max {
            get {
                return ((int)(this["Position_Roll_Max"]));
            }
            set {
                this["Position_Roll_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoConnect {
            get {
                return ((bool)(this["AutoConnect"]));
            }
            set {
                this["AutoConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int APDisconnetRollThreshold {
            get {
                return ((int)(this["APDisconnetRollThreshold"]));
            }
            set {
                this["APDisconnetRollThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int APDisconnetPitchThreshold {
            get {
                return ((int)(this["APDisconnetPitchThreshold"]));
            }
            set {
                this["APDisconnetPitchThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2000")]
        public int Position_Pitch_Min {
            get {
                return ((int)(this["Position_Pitch_Min"]));
            }
            set {
                this["Position_Pitch_Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2000")]
        public int Position_Roll_Min {
            get {
                return ((int)(this["Position_Roll_Min"]));
            }
            set {
                this["Position_Roll_Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int TorqueFactor_AirSpeed {
            get {
                return ((int)(this["TorqueFactor_AirSpeed"]));
            }
            set {
                this["TorqueFactor_AirSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int Torque_Pitch_Low {
            get {
                return ((int)(this["Torque_Pitch_Low"]));
            }
            set {
                this["Torque_Pitch_Low"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public int Torque_Pitch_High {
            get {
                return ((int)(this["Torque_Pitch_High"]));
            }
            set {
                this["Torque_Pitch_High"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int Torque_Pitch_Max {
            get {
                return ((int)(this["Torque_Pitch_Max"]));
            }
            set {
                this["Torque_Pitch_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int Torque_Roll_Low {
            get {
                return ((int)(this["Torque_Roll_Low"]));
            }
            set {
                this["Torque_Roll_Low"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public int Torque_Roll_High {
            get {
                return ((int)(this["Torque_Roll_High"]));
            }
            set {
                this["Torque_Roll_High"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int TrimFactor_Elevator {
            get {
                return ((int)(this["TrimFactor_Elevator"]));
            }
            set {
                this["TrimFactor_Elevator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int TrimFactor_Aileron {
            get {
                return ((int)(this["TrimFactor_Aileron"]));
            }
            set {
                this["TrimFactor_Aileron"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int Torque_Roll_Max {
            get {
                return ((int)(this["Torque_Roll_Max"]));
            }
            set {
                this["Torque_Roll_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2000")]
        public int Position_Pitch_HYD_OFF_Max {
            get {
                return ((int)(this["Position_Pitch_HYD_OFF_Max"]));
            }
            set {
                this["Position_Pitch_HYD_OFF_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public int APPosition_Roll_Factor {
            get {
                return ((int)(this["APPosition_Roll_Factor"]));
            }
            set {
                this["APPosition_Roll_Factor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int RS485COM_Port {
            get {
                return ((int)(this["RS485COM_Port"]));
            }
            set {
                this["RS485COM_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int Torque_Yaw_High {
            get {
                return ((int)(this["Torque_Yaw_High"]));
            }
            set {
                this["Torque_Yaw_High"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Torque_Yaw_Low {
            get {
                return ((int)(this["Torque_Yaw_Low"]));
            }
            set {
                this["Torque_Yaw_Low"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1000")]
        public int Position_Yaw_HYD_OFF_Max {
            get {
                return ((int)(this["Position_Yaw_HYD_OFF_Max"]));
            }
            set {
                this["Position_Yaw_HYD_OFF_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int APDisconnectFactor {
            get {
                return ((int)(this["APDisconnectFactor"]));
            }
            set {
                this["APDisconnectFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int TrimFactor_Rudder {
            get {
                return ((int)(this["TrimFactor_Rudder"]));
            }
            set {
                this["TrimFactor_Rudder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Enable_Rudder_ACL {
            get {
                return ((bool)(this["Enable_Rudder_ACL"]));
            }
            set {
                this["Enable_Rudder_ACL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Driver_Yaw_ID {
            get {
                return ((int)(this["Driver_Yaw_ID"]));
            }
            set {
                this["Driver_Yaw_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Driver_Pitch_ID {
            get {
                return ((int)(this["Driver_Pitch_ID"]));
            }
            set {
                this["Driver_Pitch_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Driver_Roll_ID {
            get {
                return ((int)(this["Driver_Roll_ID"]));
            }
            set {
                this["Driver_Roll_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Enable_Pitch_ACL {
            get {
                return ((bool)(this["Enable_Pitch_ACL"]));
            }
            set {
                this["Enable_Pitch_ACL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Enabe_Roll_ACL {
            get {
                return ((bool)(this["Enabe_Roll_ACL"]));
            }
            set {
                this["Enabe_Roll_ACL"] = value;
            }
        }
    }
}
